@server = http://localhost:8000/api

###
GET {{server}}/todos

###
POST {{server}}/todo
Content-Type: application/json; charset=UTF-8

{
    "title": "운동"
}

###
PATCH {{server}}/todo/2
Content-Type: application/json; charset=UTF-8

{
    "done": true
}

###
DELETE {{server}}/todo/6